import sqlite3

def create_engineering_database():
    # Connect to SQLite database (it will create the database if it doesn't exist)
    conn = sqlite3.connect('Engineering.db')
    cursor = conn.cursor()

    # Create the questions table
    cursor.execute('''CREATE TABLE IF NOT EXISTS questions (
                        id INTEGER PRIMARY KEY,
                        question TEXT,
                        option_1 TEXT,
                        option_2 TEXT,
                        option_3 TEXT,
                        option_4 TEXT,
                        correct_option TEXT,
                        difficulty TEXT)''')

    # Easy questions (120)
    easy_questions = [
        ("What is energy?", "A form of matter", "A form of power", "The ability to do work", "None of the above", "option_3"),
        ("Which of the following is renewable?", "Coal", "Solar energy", "Natural gas", "Oil", "option_2"),
        ("What is the unit of energy?", "Joule", "Watt", "Newton", "Ampere", "option_1"),
        ("Which of these is an example of a non-renewable resource?", "Wind", "Solar", "Coal", "Geothermal", "option_3"),
        ("What is the first law of thermodynamics?", "Energy cannot be created or destroyed", "Energy can be created", "Energy is lost", "None of the above", "option_1"),
        ("What is the second law of thermodynamics?", "Energy can be created", "Energy is conserved", "Heat flows from cold to hot", "Heat flows from hot to cold", "option_4"),
        ("What does the term 'energy efficiency' mean?", "Energy cannot be created", "Energy usage is minimized", "Maximizing energy output", "None of the above", "option_2"),
        ("Which of these is a method of renewable energy?", "Coal", "Natural Gas", "Wind", "Nuclear", "option_3"),
        ("What is a renewable energy resource?", "Solar", "Coal", "Oil", "Natural gas", "option_1"),
        ("Which of the following is used to measure energy?", "Watt", "Joule", "Newton", "Ampere", "option_2"),
        ("Which of these energy resources is non-renewable?", "Wind", "Solar", "Coal", "Geothermal", "option_3"),
        ("What does energy efficiency mean?", "Using more energy", "Conserving energy", "Reducing energy consumption", "None of the above", "option_3"),
        ("Which energy source is considered renewable?", "Coal", "Solar", "Natural Gas", "Oil", "option_2"),
        ("What is the unit of electric power?", "Joule", "Watt", "Ampere", "Volt", "option_2"),
        ("What is the primary source of renewable energy?", "Coal", "Solar", "Nuclear", "Natural gas", "option_2"),
        ("Which of the following energy sources is not renewable?", "Coal", "Wind", "Solar", "Hydropower", "option_1"),
        ("How is energy usually converted in wind turbines?", "Wind to heat", "Wind to electricity", "Wind to light", "Wind to sound", "option_2"),
        ("Which of the following uses energy from the sun?", "Solar panels", "Coal plants", "Wind turbines", "Hydroelectric dams", "option_1"),
        ("Which of these is a fossil fuel?", "Coal", "Solar", "Wind", "Geothermal", "option_1"),
        ("What is the process of converting solar energy into electricity called?", "Solar fusion", "Solar conversion", "Solar irradiation", "Photovoltaic conversion", "option_4"),
        ("What is the most commonly used renewable energy source?", "Solar power", "Wind energy", "Hydropower", "Geothermal energy", "option_3"),
        ("What is geothermal energy derived from?", "The sun", "The Earth's internal heat", "Wind currents", "Water evaporation", "option_2"),
        ("Which renewable energy source harnesses energy from the wind?", "Solar", "Hydropower", "Wind", "Geothermal", "option_3"),
        ("What is the main challenge in using solar energy?", "Intermittency", "Cost", "Durability", "Efficiency", "option_1"),
        ("What is a common use of bioenergy?", "Heating", "Lighting", "Cooling", "Electronics", "option_1"),
        ("Which of the following is a green energy source?", "Wind", "Coal", "Natural gas", "Oil", "option_1"),
        ("What is an advantage of using renewable energy sources?", "Unlimited availability", "Produces pollution", "High cost", "Limited resources", "option_1"),
        ("Which renewable energy is used in solar cells?", "Heat", "Wind", "Sunlight", "Water", "option_3"),
        ("What is the main disadvantage of wind energy?", "Noise", "High cost", "Intermittency", "Pollution", "option_3"),
        ("What does the term 'carbon footprint' refer to?", "The size of an energy source", "The amount of energy used", "The carbon emissions produced", "The size of a car's exhaust pipe", "option_3"),
        ("Which energy source uses the Earth’s heat?", "Hydropower", "Wind", "Geothermal", "Solar", "option_3"),
        ("Which of these does not generate energy?", "Solar panels", "Battery", "Wind turbine", "None", "option_2"),
        ("Which of the following is an example of mechanical energy?", "Heat", "Wind", "Solar", "Hydroelectric", "option_2"),
        ("Which of these is a benefit of using energy-efficient appliances?", "They cost more", "They use more electricity", "They reduce electricity consumption", "They break down easily", "option_3"),
        ("Which is a common use of geothermal energy?", "Space heating", "Running vehicles", "Lighting homes", "Cooling homes", "option_1"),
        ("Which of the following is a non-renewable resource?", "Solar", "Coal", "Wind", "Hydropower", "option_2"),
        ("What is hydropower?", "Energy from the Earth's core", "Energy from moving water", "Energy from the sun", "Energy from wind", "option_2"),
        ("What is the main advantage of renewable energy?", "Low cost", "Sustainability", "High maintenance", "No emissions", "option_2"),
        ("Which of these is an example of a renewable resource?", "Natural gas", "Wind", "Coal", "Oil", "option_2"),
        ("How do solar panels work?", "By converting heat into electricity", "By converting light into electricity", "By burning coal", "By generating electricity through wind", "option_2"),
        ("What type of energy does a battery store?", "Electrical", "Mechanical", "Chemical", "Heat", "option_3"),
        ("Which energy source uses water to produce power?", "Wind", "Solar", "Hydropower", "Coal", "option_3"),
        ("What is the primary use of a wind turbine?", "Producing heat", "Producing electricity", "Producing biofuel", "Producing hydrogen", "option_2"),
        ("Which is a key factor in improving energy efficiency?", "Increasing energy use", "Reducing energy consumption", "Decreasing energy use", "Increasing pollution", "option_2"),
        ("What does 'zero-energy' mean in terms of a building?", "It uses no energy", "It produces more energy than it uses", "It produces no carbon emissions", "It is made of sustainable materials", "option_2"),
        ("What is the most common form of renewable energy?", "Hydropower", "Solar", "Wind", "Geothermal", "option_1"),
        ("What is the primary function of energy-efficient windows?", "Increase temperature", "Reduce energy consumption", "Create wind", "Increase sunlight", "option_2"),
        ("What is the main component of natural gas?", "Carbon", "Methane", "Oxygen", "Hydrogen", "option_2"),
        ("What type of energy is produced by a dam?", "Wind energy", "Hydropower", "Geothermal", "Solar", "option_2"),
        ("What does the term 'carbon neutral' mean?", "No carbon is used", "All carbon emissions are offset", "No fossil fuels are burned", "All energy comes from solar", "option_2"),
        ("Which of the following generates electricity by using the Earth’s internal heat?", "Geothermal energy", "Wind energy", "Solar energy", "Hydropower", "option_1"),
        ("What energy source can be used to power cars?", "Natural gas", "Solar", "Wind", "Biofuel", "option_4"),
        ("What is the primary disadvantage of nuclear energy?", "High cost", "Safety concerns", "Low efficiency", "Pollution", "option_2"),
        ("What is the main source of energy for solar panels?", "Heat", "Light", "Wind", "Water", "option_2"),
        ("Which of the following is not a type of renewable energy?", "Solar", "Wind", "Nuclear", "Geothermal", "option_3"),
        ("What is the major environmental concern with burning fossil fuels?", "Pollution", "Noise", "Space usage", "Temperature drop", "option_1"),
        ("Which of the following is an energy-efficient method?", "Using incandescent bulbs", "Turning off lights when not in use", "Leaving devices plugged in", "Using more power", "option_2"),
        ("Which material is commonly used in the production of solar panels?", "Copper", "Silicon", "Aluminum", "Iron", "option_2"),
        ("Which renewable energy source uses the sun’s heat?", "Solar power", "Wind power", "Hydropower", "Geothermal", "option_1"),
        ("How is energy from the sun used?", "By burning solar panels", "By using heat", "By capturing sunlight in solar cells", "By converting sunlight to wind", "option_3"),
        ("Which of the following is an example of sustainable energy?", "Oil", "Coal", "Natural gas", "Solar power", "option_4"),
        ("What is the primary disadvantage of hydropower?", "High cost", "Pollution", "Habitat disruption", "Low efficiency", "option_3"),
        ("Which of the following is a way to save energy in the home?", "Use more electricity", "Use energy-efficient appliances", "Leave lights on", "Use fossil fuels", "option_2"),
        ("What is the primary purpose of an energy audit?", "To find new energy sources", "To measure energy consumption", "To predict energy consumption", "To increase energy efficiency", "option_2"),
        ("Which of these is an example of mechanical energy?", "Electricity", "Wind", "Chemical energy", "Solar energy", "option_2"),
        ("What is a key feature of energy-efficient lighting?", "It generates more heat", "It uses more power", "It uses less energy for the same brightness", "It lasts shorter", "option_3"),
        ("What is the most common energy source for power plants?", "Coal", "Solar", "Wind", "Nuclear", "option_1"),
        ("Which of these is a renewable source of energy?", "Oil", "Wind", "Natural gas", "Coal", "option_2"),
        ("Which energy source produces the least pollution?", "Wind", "Coal", "Natural gas", "Oil", "option_1"),
        ("Which energy resource is primarily used for heating and cooking?", "Wind", "Geothermal", "Solar", "Biomass", "option_4"),
        ("What is the key feature of an energy-efficient appliance?", "Uses more energy", "Consumes less energy", "Is smaller", "Is cheaper", "option_2"),
        ("Which of the following is a potential use of geothermal energy?", "Heating homes", "Lighting homes", "Fueling cars", "Generating electricity", "option_1"),
        ("Which of these methods is used to convert wind energy into electricity?", "Turbines", "Solar cells", "Coal plants", "Hydropower", "option_1"),
        ("What does energy efficiency measure?", "How much energy is used", "How little energy is wasted", "The total energy generated", "The source of energy", "option_2"),
        ("Which of the following is an example of kinetic energy?", "A car moving", "A battery", "A solar panel", "A heating system", "option_1"),
        ("What is the main disadvantage of using biomass?", "It requires land", "It generates pollution", "It requires water", "It produces too much heat", "option_2"),
        ("What is wind energy converted into?", "Heat", "Mechanical energy", "Electricity", "Light", "option_3"),
        ("Which of these energy sources is commonly used in rural areas?", "Wind", "Solar", "Natural gas", "Coal", "option_2"),
        ("What type of energy does a power plant use?", "Geothermal", "Solar", "Fossil fuel", "Wind", "option_3"),
        ("Which of these is an example of a non-renewable resource?", "Solar", "Wind", "Natural gas", "Geothermal", "option_3"),
]


    # Medium questions (120)
    medium_questions = [
        ("What is the most efficient energy storage system?", "Batteries", "Pumped hydro", "Compressed air", "Flywheels", "option_2"),
        ("Which of the following is a renewable energy source?", "Coal", "Solar power", "Natural gas", "Nuclear power", "option_2"),
        ("How is electricity generated in nuclear power plants?", "By burning fossil fuels", "By nuclear fission", "By water movement", "By wind turbines", "option_2"),
        ("What is a key feature of energy-efficient lighting?", "It generates more heat", "It uses more power", "It uses less energy for the same brightness", "It lasts shorter", "option_3"),
        ("What does the term 'carbon footprint' refer to?", "The amount of energy used", "The amount of carbon dioxide produced", "The total energy capacity", "The carbon dioxide emissions from forests", "option_2"),
        ("Which of these is an energy-efficient material?", "Aluminum", "Steel", "Copper", "Plastic", "option_1"),
        ("Which of the following is a type of energy storage?", "Solar power", "Wind turbines", "Batteries", "Hydropower", "option_3"),
        ("How does a photovoltaic cell work?", "By generating heat", "By converting light to electricity", "By using chemical energy", "By burning fuel", "option_2"),
        ("What is an example of energy conservation?", "Turning off lights", "Using more electricity", "Using fossil fuels", "Burning more coal", "option_1"),
        ("What is the primary disadvantage of solar power?", "High costs", "Inconsistent availability", "Efficient energy conversion", "Requires large land area", "option_2"),
        ("Which of the following is used to measure power?", "Watt", "Joule", "Newton", "Ampere", "option_1"),
        ("What is the primary function of an energy audit?", "To find new energy sources", "To measure energy consumption", "To predict energy consumption", "To increase energy efficiency", "option_2"),
        ("Which of the following is not a renewable energy source?", "Solar", "Wind", "Natural gas", "Geothermal", "option_3"),
        ("What type of energy conversion occurs in a wind turbine?", "Mechanical to electrical", "Electrical to mechanical", "Chemical to mechanical", "Heat to electricity", "option_1"),
        ("What is the most common type of energy storage?", "Pumped hydro", "Flywheels", "Batteries", "Compressed air", "option_3"),
        ("What is a key principle of sustainable energy?", "Using fossil fuels", "Maximizing energy consumption", "Reducing energy waste", "Increasing emissions", "option_3"),
        ("Which of the following is a greenhouse gas?", "Oxygen", "Nitrogen", "Carbon dioxide", "Argon", "option_3"),
        ("What is the principle behind geothermal energy?", "Energy from the sun", "Energy from wind", "Energy from the Earth's heat", "Energy from water", "option_3"),
        ("What does the term 'energy efficiency' mean?", "Using more energy", "Using less energy to perform the same task", "Energy consumption increase", "Using energy in any form", "option_2"),
        ("What is the energy conversion process in a hydropower plant?", "Kinetic to electrical", "Chemical to mechanical", "Heat to electrical", "Mechanical to chemical", "option_1"),
        ("Which of the following is an advantage of solar energy?", "High maintenance costs", "Requires no fuel", "High land requirements", "Pollution generation", "option_2"),
        ("What is an advantage of wind power?", "It is location-independent", "It generates pollution", "It requires a large land area", "It is dependent on weather conditions", "option_4"),
        ("What is a significant disadvantage of nuclear power?", "High operating costs", "Pollution", "Safety risks", "Waste disposal issues", "option_3"),
        ("Which of the following is not a method of reducing energy consumption?", "Switching to energy-efficient appliances", "Using incandescent light bulbs", "Turning off unused lights", "Improving building insulation", "option_2"),
        ("What is the efficiency of a typical coal-fired power plant?", "90-95%", "40-45%", "50-55%", "65-70%", "option_2"),
        ("Which of these is a major challenge when using renewable energy sources?", "Availability and intermittency", "High cost", "Low efficiency", "Lack of technology", "option_1"),
        ("Which energy storage system is used in pumped hydro storage?", "Water", "Compressed air", "Batteries", "Flywheels", "option_1"),
        ("What is the most common energy storage system for grid-scale energy storage?", "Batteries", "Pumped hydro", "Flywheels", "Compressed air", "option_2"),
        ("What is the primary function of energy-efficient windows?", "Increase heat", "Reduce heat loss", "Increase light", "Reduce light", "option_2"),
        ("What is the role of a smart grid in energy management?", "Reduce energy consumption", "Improve energy efficiency", "Distribute power evenly", "Allow remote power generation", "option_2"),
        ("What is a common renewable energy system used for heating water?", "Solar water heating", "Wind turbines", "Geothermal heat pumps", "Biomass", "option_1"),
        ("What is the difference between a renewable and non-renewable resource?", "Renewables are finite", "Renewables are limitless", "Non-renewables last indefinitely", "Non-renewables replenish every year", "option_2"),
        ("Which of the following is a major use of bioenergy?", "Heating", "Lighting", "Cooling", "Electricity generation", "option_1"),
        ("What is a typical application of geothermal energy?", "Heating homes", "Powering vehicles", "Lighting buildings", "Cooling homes", "option_1"),
        ("Which of the following is an example of an energy-efficient building material?", "Concrete", "Wood", "Insulated glass", "Plaster", "option_3"),
        ("How does an electric vehicle reduce energy consumption?", "By using gasoline", "By using electricity from renewable sources", "By using natural gas", "By using more power", "option_2"),
        ("Which of the following is an example of a passive energy design in buildings?", "Solar panels", "Wind turbines", "Green roofs", "Orientation of windows to capture sunlight", "option_4"),
        ("Which renewable energy source uses kinetic energy to generate power?", "Wind", "Solar", "Geothermal", "Hydropower", "option_1"),
        ("Which of these is an energy-efficient material?", "Aluminum", "Copper", "Glass", "Plastic", "option_1"),
        ("What is the main purpose of energy conservation?", "To increase energy consumption", "To reduce costs and reduce emissions", "To increase electricity generation", "To improve efficiency", "option_2"),
        ("Which of the following is a challenge for solar power?", "Requires large land area", "High cost", "Energy storage", "Pollution", "option_3"),
        ("What is the major environmental concern with wind energy?", "Noise", "Land use", "Bird collisions", "Water pollution", "option_3"),
        ("How does hydroelectric power generate electricity?", "Using chemical energy", "Using thermal energy", "Using kinetic energy from water flow", "Using wind", "option_3"),
        ("What is one of the benefits of using energy-efficient appliances?", "Increased energy consumption", "Lower cost", "Increased carbon emissions", "Reduced energy use", "option_4"),
        ("Which of the following is an advantage of using LED bulbs?", "High energy consumption", "They use less energy", "They produce more heat", "They need frequent replacement", "option_2"),
        ("Which of these is used for measuring energy consumption?", "Kilowatt-hour", "Joule", "Watt", "Volt", "option_1"),
        ("What is the main benefit of using a hybrid vehicle?", "Increased fuel consumption", "Reduced emissions", "Increased carbon footprint", "Decreased efficiency", "option_2"),
        ("What is the key environmental issue related to hydraulic fracturing?", "Air pollution", "Water contamination", "Noise", "Carbon emissions", "option_2"),
        ("How do wind turbines convert energy?", "By using thermal energy", "By using kinetic energy", "By using electrical energy", "By using light energy", "option_2"),
        ("Which of the following is not considered a renewable resource?", "Natural gas", "Solar energy", "Wind energy", "Geothermal energy", "option_1"),
        ("What is the environmental impact of using coal for energy?", "It is carbon neutral", "It produces carbon emissions", "It reduces air pollution", "It creates sustainable energy", "option_2"),
        ("Which of the following energy sources does not emit greenhouse gases?", "Solar energy", "Coal", "Oil", "Natural gas", "option_1"),
        ("What is the main challenge of nuclear energy?", "Cost", "Safety and waste disposal", "Emissions", "Efficiency", "option_2"),
        ("Which of these is a non-renewable resource?", "Coal", "Wind", "Solar", "Geothermal", "option_1"),
        ("What is the process of turning sunlight into energy called?", "Solar fusion", "Solar conversion", "Photovoltaic", "Solar energy", "option_3"),
        ("What is the main purpose of a wind turbine?", "Heating homes", "Generating electricity", "Reducing carbon emissions", "Providing insulation", "option_2"),
        ("What is the primary use of geothermal energy?", "Heating", "Cooling", "Electricity generation", "Wind power", "option_3"),
        ("Which of the following is the most used renewable energy in the world?", "Wind", "Hydropower", "Solar", "Geothermal", "option_2"),
        ("Which of these is used to store energy in the form of compressed air?", "Flywheel", "Pumped storage", "Compressed air storage", "Hydroelectric storage", "option_3"),
        ("What is the environmental impact of hydroelectric power?", "Minimal pollution", "No impact", "High carbon emissions", "Water contamination", "option_1"),
    ]


    # Hard questions (60)
    hard_questions = [
        ("In which year was the first law of thermodynamics formulated?", "1830", "1850", "1900", "1905", "option_2"),
        ("What is the most efficient way to store solar energy?", "In batteries", "In compressed air", "In thermal systems", "In hydrogen", "option_3"),
        ("Which material is commonly used in the production of solar panels?", "Copper", "Silicon", "Iron", "Aluminum", "option_2"),
        ("What does 'peak demand' refer to in energy production?", "The highest level of energy production", "The highest level of energy consumption", "The lowest level of energy consumption", "The amount of energy lost", "option_2"),
        ("What is the principle behind geothermal energy?", "Using heat from the sun", "Using heat from the Earth's core", "Burning fossil fuels", "Harnessing wind energy", "option_2"),
        ("What is the most efficient method for reducing carbon emissions?", "Burning coal", "Solar power", "Wind power", "Nuclear energy", "option_2"),
        ("Which of these is an example of bioenergy?", "Coal", "Wind power", "Wood", "Natural gas", "option_3"),
        ("What technology is used in carbon capture?", "Nuclear fusion", "Photosynthesis", "Absorption", "Wind turbines", "option_3"),
        ("How does geothermal energy work?", "By using sunlight", "By using Earth's heat", "By burning fossil fuels", "By water evaporation", "option_2"),
        ("Which of the following is the most efficient energy conversion technology?", "Coal plants", "Hydropower", "Natural gas", "Solar panels", "option_2"),
        ("Which of the following energy conversion systems has the highest efficiency?", "Coal-fired power plants", "Nuclear reactors", "Hydropower plants", "Wind turbines", "option_2"),
        ("What is the principle of operation of a fuel cell?", "Electrochemical conversion of fuel to energy", "Burning of fuel", "Using sunlight to generate electricity", "Using heat to generate power", "option_1"),
        ("Which of the following is used to store energy in hydrogen?", "Batteries", "Compressed air", "Hydrogen fuel cells", "Hydrogen tanks", "option_4"),
        ("In which energy storage system does energy come from the movement of water?", "Pumped hydro storage", "Flywheel storage", "Battery storage", "Compressed air storage", "option_1"),
        ("What is the main disadvantage of nuclear power?", "High capital cost", "Low energy output", "High environmental impact", "Waste disposal issues", "option_4"),
        ("What is the main environmental challenge associated with fracking?", "Air pollution", "Water contamination", "Soil erosion", "Noise pollution", "option_2"),
        ("What is the principle of a geothermal heat pump?", "Converting heat from the Earth's crust", "Harnessing heat from the sun", "Using underground water systems", "Pumping water from deep underground", "option_1"),
        ("Which of the following is a disadvantage of using wind energy?", "High maintenance costs", "Noise pollution", "High capital costs", "Unreliable source of energy", "option_2"),
        ("Which of these technologies is used to capture and store carbon emissions?", "Solar panels", "Carbon capture and storage", "Nuclear fusion", "Wind turbines", "option_2"),
        ("Which of these technologies is associated with energy efficiency?", "Thermal insulation", "Solar panels", "Geothermal energy", "Wind turbines", "option_1"),
        ("What is the main advantage of using hydrogen as an energy source?", "It can be stored easily", "It is a renewable resource", "It is abundant and cost-effective", "It emits no greenhouse gases when used", "option_4"),
        ("What is the process by which wind turbines generate electricity?", "Wind energy is converted into thermal energy", "Wind energy is converted into mechanical energy", "Wind energy is converted into electrical energy", "Wind energy is converted into chemical energy", "option_3"),
        ("Which of the following is an example of a carbon-neutral energy source?", "Coal", "Natural gas", "Wind energy", "Solar power", "option_3"),
        ("How does the use of renewable energy help in reducing carbon emissions?", "By reducing the need for fossil fuels", "By increasing the energy demand", "By using more fossil fuels", "By creating more waste", "option_1"),
        ("What is a challenge when using bioenergy?", "Limited supply", "Carbon emissions", "Cost-effectiveness", "Land use", "option_4"),
        ("What is the key feature of a photovoltaic cell?", "It converts light into heat", "It generates electricity through heat", "It converts sunlight into electricity", "It absorbs carbon dioxide", "option_3"),
        ("What type of energy conversion occurs in a thermoelectric generator?", "Heat to electricity", "Electricity to heat", "Mechanical to electricity", "Heat to mechanical energy", "option_1"),
        ("What is the major disadvantage of using coal as an energy source?", "High efficiency", "High carbon emissions", "Renewable source", "Low cost", "option_2"),
        ("Which of the following is used in a tidal energy system?", "Solar panels", "Wind turbines", "Turbines powered by tidal flow", "Batteries", "option_3"),
        ("What is the main principle of a biomass power plant?", "Burning biomass for energy", "Using geothermal heat", "Converting sunlight into heat", "Storing wind energy", "option_1"),
        ("Which of the following technologies is best suited for large-scale energy storage?", "Batteries", "Compressed air", "Pumped hydro storage", "Flywheel energy storage", "option_3"),
        ("Which of these energy storage technologies is known for having the longest lifespan?", "Batteries", "Flywheels", "Compressed air", "Pumped hydro storage", "option_4"),
        ("What is the primary concern with using coal as an energy source?", "Increased efficiency", "Carbon emissions and pollution", "Cost", "Energy storage", "option_2"),
        ("Which type of power generation does not use fossil fuels?", "Nuclear power", "Geothermal power", "Wind power", "Solar power", "option_4"),
        ("Which of these materials is commonly used in the construction of wind turbine blades?", "Copper", "Aluminum", "Fiberglass", "Plastic", "option_3"),
        ("Which of these technologies can provide baseload power?", "Solar energy", "Wind energy", "Nuclear energy", "Hydropower", "option_3"),
        ("Which renewable energy source has the least environmental impact?", "Wind", "Solar", "Hydropower", "Geothermal", "option_1"),
        ("What is the advantage of using combined heat and power (CHP) systems?", "Increased energy consumption", "Reduction in heat energy waste", "Increase in emissions", "Higher electricity costs", "option_2"),
        ("What type of energy is used in nuclear reactors?", "Solar energy", "Fission energy", "Chemical energy", "Geothermal energy", "option_2"),
        ("What is the role of a flywheel in energy storage systems?", "To convert mechanical energy into electrical energy", "To store rotational energy", "To generate electricity from wind", "To generate heat", "option_2"),
        ("What is the key advantage of using tidal energy?", "It is a non-renewable resource", "It is highly predictable", "It requires large land areas", "It has a high environmental impact", "option_2"),
        ("What is the primary environmental concern associated with hydropower?", "Water contamination", "Ecosystem disruption", "Air pollution", "Carbon emissions", "option_2"),
        ("What is the main limitation of solar energy?", "High cost of installation", "Limited energy production in cloudy weather", "Limited energy storage options", "Low energy efficiency", "option_2"),
        ("What technology is used in energy-efficient buildings?", "Solar energy", "Thermal insulation", "Wind turbines", "Hydropower", "option_2"),
        ("Which of the following is an example of an energy-efficient transportation system?", "Electric cars", "Coal-powered trains", "Gasoline-powered cars", "Nuclear-powered ships", "option_1"),
        ("Which energy resource is often considered 'clean' because it emits very low amounts of greenhouse gases?", "Coal", "Natural gas", "Wind", "Geothermal", "option_3"),
        ("What is the main concern regarding the disposal of nuclear waste?", "It is radioactive", "It requires large storage sites", "It produces harmful chemicals", "It cannot be reused", "option_1"),
        ("What energy source is used in the production of hydrogen fuel cells?", "Fossil fuels", "Renewable energy", "Biofuels", "Electricity from grid", "option_2"),
        ("What does the term 'distributed generation' refer to?", "Energy generation from large centralized plants", "Energy generation from small local sources", "Energy generation using fossil fuels", "Energy production from solar panels", "option_2"),
        ("Which of the following energy sources is the least polluting?", "Coal", "Natural gas", "Wind", "Geothermal", "option_3"),
        ("What is the main advantage of using wind energy?", "It produces no emissions", "It is highly reliable", "It generates heat", "It requires little land", "option_1"),
        ("What is one of the main issues with the use of biomass as an energy source?", "Requires too much land", "Produces high emissions", "Is non-renewable", "Is highly expensive", "option_1"),
        ("Which of the following is a potential risk associated with geothermal energy?", "Earthquakes", "Radioactive waste", "Water contamination", "Air pollution", "option_3"),
        ("Which of these is used to store energy from solar panels?", "Batteries", "Wind turbines", "Flywheels", "Pumped hydro storage", "option_1"),
        ("What is the most efficient energy conversion process in solar power plants?", "Converting solar heat to electricity", "Converting sunlight to electricity", "Converting solar heat to chemical energy", "Converting sunlight to heat", "option_2"),
        ("Which renewable energy source is most affected by geographic location?", "Geothermal", "Wind", "Solar", "Hydropower", "option_2"),
        ("Which energy resource produces the least amount of waste?", "Wind", "Coal", "Natural gas", "Geothermal", "option_1"),
    ]


    # Function to insert questions into the database
    def insert_questions(questions, difficulty):
        for q in questions:
            cursor.execute('''INSERT INTO questions (question, option_1, option_2, option_3, option_4, correct_option, difficulty)
                              VALUES (?, ?, ?, ?, ?, ?, ?)''', (*q, difficulty))

    # Insert all questions into the database
    insert_questions(easy_questions, "Easy")
    insert_questions(medium_questions, "Medium")
    insert_questions(hard_questions, "Hard")

    # Commit the changes and close the connection
    conn.commit()
    conn.close()

# Create the database and populate it with questions
create_engineering_database()
print("Engineering database created and populated successfully!")
